moccasin/commands/compile.py
for performance reasons, vyper exceptions can have lambdas in them. resolve the lambdas before raising to the parent process
=> fix a parallelization bug

moccasin/commands/install.py, moccasin/fixture_tools.py
- remove module param from request_fixture
- rewrite module finding routine, it is now invariant to stack depth
- fixture_name defaults to None
- simplify request_fixture, remove make_fixture
- simplify fixture creation
=> refactor: cleanup fixture_tools

moccasin/commands/compile.py
the pickling/unpickling of the VyperDeployer was a perf bottleneck. it's not used, so don't return it from the subprocess
=> fix: fix perf bug in `mox compile`

docs/source/how-tos/juypter_notebooks.rst, docs/source/toctree.rst, moccasin/__init__.py, moccasin/_sys_path_and_config_setup.py, moccasin/config.py, pyproject.toml, uv.lock
Now, users can enter a `.ipynb` notebook and run:
```python
from moccasin import setup_notebook
setup_notebook()
```
```python
from moccasin.config import get_active_network
active_network = get_active_network()
eth_usd = active_network.manifest_named("eth_usd_price_feed")
```
And it'll auto-pull in their config files, change the python environment, and such.
=> feat: notebook setup

tests/data/deployments_project/.coveragerc, tests/data/purge_project/.coveragerc, tests/data/tests_project/.coveragerc
There were three .coveragerc files with multiple empty lines which was addressed in Issue #173 . This PR contains 3 commits which remove them.
=> Remove Empty Lines in Default Files (Issue #173)

tests/data/complex_project/contracts/InitializedAuth.vy, tests/data/complex_project/contracts/UninitializedAuth.vy, tests/data/installation_project/src/MyToken.vy
**Related** to: #181
**OS**: Ubuntu24
**Mox version**: Moccasin CLI v0.3.6
---
Just test command failed due to wrong typo on Vyper module `import PatrickAlphaC.test_repo`
-> Fixed import in Vyper related file
```vy
from patrickalphac.test_repo import my_contract
```
Found other import failure on module `Auth` imported like auth initially:
```vy
import auth
```
-> Fixed import by using aliases
```vy
import Auth as auth
```
=> Correct typo module imports for `just test` CLI and unit fix #181

docs/source/installing_moccasin.rst, docs/source/quickstart.rst
Issue: #26 
Proposal for a documentation about poetry project with Moccasin.
- Inspired from `pipx` doc install support
- Tested locally by initializing a project and understanding how poetry handle virtual environments
- Adapted Quickstart section  too since we should init the subfolder of a poetry project (directory structure of poetry)
---
Hope it responds to the original issue. Feel free to check and clarify some points (or all of it)  :+1:
=> Doc: poetry installation support to add moccasin for #26

docs/source/api_reference/config_reference.rst, moccasin/config.py
Related Issue: #86 
---
Updated the `moccasin.config.Config` class docstrings for most of the members. Tested with HTML versions with `just docs`.
I applied the `bysource` order since `groupwise` was not doing the job and default `alphabetical` was not adequate.
Ref: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-option-autoclass-members
Sphinx way used to comply with `[reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html)`
I did not make the `properties` but if it is required, feel free to ask. I did not add the `:private-member:` options too but it can be added to show it in the doc.
Any feedbacks are welcome!
=> [Issue#86] - Doc - Update class config docstring sphinx style and adapt rst file

tests/integration/README.md
Related issue: #187 
---
Updated README for integration test with `just test-i`.  With a little tip at the end (not developed but if needed I can).
```bash
EXPLORER_API_KEY
OPTIMISTIC_ETHERSCAN_API_KEY
MAINNET_RPC_URL
```
=> [Issue#187] - Doc - Update readme for integration test with right env values needed

docs/source/all_moccasin_toml_parameters.rst, docs/source/core_concepts/networks.rst, docs/source/core_concepts/networks/forked_networks.rst, moccasin/constants/vars.py
Current docs use `is_fork`, should be `fork`
=> fix: docs - fix toml key for forking

docs/source/core_concepts/networks/forked_networks.rst, moccasin/config.py, moccasin/constants/vars.py, tests/data/complex_project/moccasin.toml
Currently the block at which a chain is forked is not configurable and defaults to `safe`. Users may however want to run tests at specific blocks in the past. Furthermore RPCs for chains like Polygon often fail when trying to fetch a safe block.
I added the option to the `complex_project`'s config file, but did not write a specific test for it. If you would like a specific test, please let me know where.
=> Add block_identifier to config to support forking at a specific block

moccasin/__main__.py, moccasin/commands/compile.py, moccasin/commands/init.py, moccasin/constants/vars.py
Related issue: #186 
---
- `init.py`: Windows error `(UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f40d')` when the param `encoding="utf-8" for `open` is not set
- `compile.py`: Windows does not support `fork` method for `multiprocessing.set_start_method()`, hence changed to "spawn"
- `vars.py`: added general constant `IS_WINDOWS` for future use and avoid any duplicates
- fixed utils CLI command running an error when no arguments passed + fixed some var typo
=> [Issue-#186] - Fix - Windows issues on mox cli command and utils argparser

moccasin/config.py
Pass on network information to boa_get_abi_from_explorer when manifesting named contracts
Fixes #194
=> Pass on network information to boa_get_abi_from_explorer

tests/cli/deployments/conftest.py, tests/cli/test_cli_run.py, tests/cli/test_cli_test.py, tests/cli/test_cli_wallet.py, tests/conftest.py, tests/constants.py, tests/data/complex_project/moccasin.toml, tests/integration/test_integration_explorer.py, tests/integration/test_integration_install.py, tests/integration/test_integration_purge.py, tests/live/test_live_verify.py, tests/unit/test_unit_run.py, tests/unit/test_unit_wallet.py, tests/zksync/conftest.py, tests/zksync/test_unit_zksync.py, uv.lock
No related issue
---
- Moving constants inside their proper file under tests' folder → avoid import `tests.conftest` and keep it as fixture file
- Adapt import from `tests.conftest` to `tests.constants` with constant uppercase naming → adapted
- Fix `moccasin.toml` explorer_uri for live testing
=> Rework - Move conftest const in their file and adapt import in test files

docs/source/api_reference/network_reference.rst, moccasin/config.py, uv.lock
Related issue: #86 
---
- Class and methods docstring added
- Updated logging messages for deprecated method around `get_or_deploy_named` method
- Updated rst config network for ordering `bysource`
=> Docs - Add docstring sphinx typo for network class

docs/source/api_reference/moccasin_account_reference.rst, docs/source/api_reference/named_contract_reference.rst, moccasin/config.py, moccasin/moccasin_account.py, moccasin/named_contract.py
Related Issue: #86 
---
- Docstring added for ``NamedContract`` and ``MoccasinAccount``
- Refactor docstring ``param`` and ``ivar`` for clarity
- Moved docstring params from ``__init__`` to class docstring to show in official doc
I adapted `param` and `ivar` because I understood that `@dataclass` make the `__init__` automatically from the variables declared in the class. So they are not variables used during runtime but actual `params` to init the class.
=> docs: NamedContract and MoccasinAccount class ref for #86

.devcontainer/devcontainer.json
- fix ``/bin/sh: 1: source: not found`` error in devcontainer terminal by forcing zsh shell for ``source .venv/bin/activate``
=> fix: apply zsh shell in postCreateCommand for #223

.devcontainer/devcontainer.json, .vscode/settings.json
- avoid ``"python.terminal.activateEnvironment": false,`` in ``.vscode/settings.json`` -> it should not activate locally if not checked in personal settings
- add ``"python.terminal.activateEnvironment": true,`` in ``devcontainer.json`` -> now venv is activated in devcontainer terminal everytime
- add ruff and better toml support in devcontainer for better vscode experience
Issue: #224
=> feat: improve devcontainer setup environment for #224

.devcontainer/Dockerfile, uv.lock
This pull request updates the version of `zkvyper` used in the `.devcontainer/Dockerfile` to ensure compatibility with the latest features and fixes.
* Updated the `ZKVYPER_VERSION` environment variable from `1.5.7` to `1.5.10` to use the latest release of `zkvyper`. (`.devcontainer/Dockerfile`, [.devcontainer/DockerfileL48-R48](diffhunk://#diff-13bd9d7a30bf46656bc81f1ad5b908a627f9247be3f7d76df862b0578b534fc6L48-R48))
Related to recent fix/release of `titanoboa-zksync` -> https://github.com/vyperlang/titanoboa-zksync/pull/44
=> feat: update zkvyper to 1.5.10 in dev container

.github/workflows/docs-release.yml, .github/workflows/pypi-release.yml, .github/workflows/typecheck-and-formatting.yml
Updated astral-sh/setup-uv from v2 to v6 across all workflow files to ensure compatibility with the latest features and improvements.
=> Update setup-uv action to latest version v6

README.md
corrected a couple of small language issues in the documentation. specifically:  
- removed the extra "to" in the phrase "to for."  
- corrected "stated" to "started" for proper tense usage.
=> docs: fix minor language issues in documentation

.devcontainer/Dockerfile, pyproject.toml, uv.lock
This pull request includes updates to dependencies and metadata in the project. The most important changes involve upgrading the `anvil-zksync` version in the Dockerfile and modifying license-related metadata in the `pyproject.toml` file.
* [`.devcontainer/Dockerfile`](diffhunk://#diff-13bd9d7a30bf46656bc81f1ad5b908a627f9247be3f7d76df862b0578b534fc6L35-R35): Upgraded `anvil-zksync` from version `0.3.2` to `0.6.0` to ensure compatibility with the latest features and fixes.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L38-L39): Removed duplicate license classifiers (`MIT License` and `Apache Software License`) and added `license-files` pointing to `LICENSE-MIT` and `LICENSE-APACHE`.
* fix license classifiers deprecation due to …
=> build: bump anvil-zksync to 0.6.0 and fix license

docs/source/core_concepts/testing/coverage.rst, docs/source/core_concepts/testing/fuzzing.rst, docs/source/core_concepts/testing/gas_profiling.rst, docs/source/core_concepts/testing/titanoboa_testing.rst
In `docs/source/core_concepts/testing/fuzzing.rst`, replace plain hyperlink syntax with reStructuredText's `:doc:` directive for better integration with Sphinx documentation tools.
Documentation improvements:
* Updated links to `Stateless Fuzzing` and `Stateful Fuzzing` guides to use the `:doc:` directive for improved Sphinx compatibility. [[1]](diffhunk://#diff-5e2b66c0385958b21cb9a813a2b3a1bc905e68c5928820e36d3e77d4264704feL8-R9) [[2]](diffhunk://#diff-5e2b66c0385958b21cb9a813a2b3a1bc905e68c5928820e36d3e77d4264704feL157-R158)
=> fix: broken link for fuzzing in doc

.github/workflows/docs-release.yml, .github/workflows/typecheck-and-formatting.yml
Using the latest v3 gives better compatibility, stability, and future-proofing.
Official v3 release is confirmed here → [setup-just@v3](https://github.com/extractions/setup-just/releases)
=> Update setup-just to v3

moccasin/commands/install.py, tests/cli/test_cli_compile.py, tests/cli/test_cli_install.py, tests/constants.py, tests/integration/test_integration_compile.py, tests/integration/test_integration_deploy.py, tests/integration/test_integration_install.py
Changes added in #236, but since it is a complex feature, I exported the unrelated changes in a different refactor branch.
It will ease the review and allow for non-blocking features to pass while working on the complexity.
---
- Fix default library directory installation to actually work as expected.
- Adapt tests to reflect the new default library directory installation.
- Update constants related to package versions.
=> refactor: default installation of lib directory and adapt test env 

moccasin/__main__.py, moccasin/commands/format.py, moccasin/commands/vyper.py, pyproject.toml, tests/cli/test_cli_format.py, tests/cli/test_cli_vyper.py, tests/data/complex_project/contracts/Auth.vy, tests/data/complex_project/contracts/BuyMeACoffee.vy, tests/data/complex_project/contracts/Counter.vy, tests/data/complex_project/contracts/InitializedAuth.vy, tests/data/complex_project/contracts/UninitializedAuth.vy, tests/data/complex_project/contracts/mocks/MockV3Aggregator.vy, uv.lock
Add a `vyper` command to moccasin's CLI that allows to run vyper with moccasin's dependency resolution.
This allows to use the vyper formatting functions for interface or abi generation within a moccasin project that uses dependencies installed with moccasin.
=> feat: add vyper to mox CLI

docs/source/common_errors.rst
This pull request updates the `docs/source/common_errors.rst` file to include detailed explanations and solutions for several common errors encountered in discussion tab of mox full course. These additions aim to improve user troubleshooting by providing clear guidance for resolving issues related to missing directories, version mismatches, and deployment errors.
* **FileNotFoundError**:
- Added explanation for the error caused by a missing `lib` directory and its subdirectories (`github` and `pypi`).
- Provided instructions to manually create the directories or use the `mox install` command to generate them automatically.
* **VersionException**:
- Documented the issue with incompatible Vyper versions when using the VSCode Vyper extension.
- Suggested updating the `vyper.command` setting …
=> docs: update common errors documentation
